name: update-site

on:
  repository_dispatch:
    types: test-me
  schedule:
  - cron:  '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: colobas/covid19-rmarkdown:latest
    steps:
    - uses: actions/checkout@master
    - name: run-script
      run: |
        Rscript -e "rmarkdown::render('dashboard.Rmd')"
        mv dashboard.html docs/index.html
    - name: commit-changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Automated update"
        git commit -m "Automated update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.covid19 }}
