name: update-site

 on:
   repository_dispatch:
     types: test-me
   schedule:
   - cron:  '5 20 * * *'

 jobs:
   build:
     runs-on: ubuntu-latest
     container: colobas/covid19-rmarkdown:latest
     steps:
     - name: run-script
       run: |
         Rscript -e "rmarkdown::render('dashboard.Rmd')"
         mv index.html docs
     - name: commit-changes
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "Automated update"
         git commit -m "Automated update" -a
     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.covid19 }}
